### ISSUE TITLE
run.sh with command line parsing of arguments

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [asdcid/Haplotig-separation#2]
Hi Raymond,
Looks great. I think it will be way easier for users to use command line options of run.sh and not have to fix the script. The outputdir could be a basename of the genome with timestamp.

I would simply query if mummer and blast is in the path and raise an error if not. Folks will need to fix it if not. Would be easier as well I think.

**Comment by asdcid** [comment]
Done
