### ISSUE TITLE
scripts need to be all in the same folder

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [asdcid/Haplotig-separation#3]
Hi Raymond,
Right now all the scripts need to be in the same folder to run. Maybe worth considering to make a script folder and move everything except for the run script (run.sh could be also renamed to something memorable). Ideally, only run.sh would add up in the path and it would know where all the depend scripts ended up.

Thanks!
Benjamin

**Comment by asdcid** [comment]
Done
